name: Bitbar Testing User Documentation
markdown: kramdown
highlighter: rouge
#url: http://docs.testdroid.com
#baseurl: /testdroid-documentation
gems:
  - jekyll-sitemap
exclude:
  - fix-image.sh
  - Gemfile
  - Gemfile.lock
  

td_link: "[Bitbar Testing](http://bitbar.com/)"
td_cloud: "[Bitbar Testing Cloud](http://cloud.testdroid.com/)"
